/** Top 100 cryptocurrencies by market cap (CoinGecko snapshot, Oct 2026). Prices are static samples; logos are bundled in public/crypto. */
export type CryptoAsset = { id: string; symbol: string; name: string; price: number; logo: string };

export const CRYPTO_CATALOG: CryptoAsset[] = [
  { id: "bitcoin", symbol: "BTC", name: "Bitcoin", price: 86306, logo: "crypto/bitcoin.png" },
  { id: "ethereum", symbol: "ETH", name: "Ethereum", price: 2718.19, logo: "crypto/ethereum.png" },
  { id: "tether", symbol: "USDT", name: "Tether", price: 0.9999, logo: "crypto/tether.png" },
  { id: "binancecoin", symbol: "BNB", name: "BNB", price: 794.77, logo: "crypto/binancecoin.png" },
  { id: "ripple", symbol: "XRP", name: "XRP", price: 1.52, logo: "crypto/ripple.png" },
  { id: "usd-coin", symbol: "USDC", name: "USDC", price: 1, logo: "crypto/usd-coin.png" },
  { id: "solana", symbol: "SOL", name: "Solana", price: 121.97, logo: "crypto/solana.png" },
  { id: "tron", symbol: "TRX", name: "TRON", price: 0.3357, logo: "crypto/tron.png" },
  { id: "figure-heloc", symbol: "FIGR_HELOC", name: "Figure Heloc", price: 1.07, logo: "crypto/figure-heloc.png" },
  { id: "zcash", symbol: "ZEC", name: "Zcash", price: 1355.96, logo: "crypto/zcash.png" },
  { id: "hyperliquid", symbol: "HYPE", name: "Hyperliquid", price: 91.11, logo: "crypto/hyperliquid.jpg" },
  { id: "dogecoin", symbol: "DOGE", name: "Dogecoin", price: 0.09669, logo: "crypto/dogecoin.png" },
  { id: "chainlink", symbol: "LINK", name: "Chainlink", price: 14.3, logo: "crypto/chainlink.png" },
  { id: "monero", symbol: "XMR", name: "Monero", price: 549.56, logo: "crypto/monero.png" },
  { id: "whitebit", symbol: "WBT", name: "WhiteBIT Coin", price: 85.68, logo: "crypto/whitebit.png" },
  { id: "usds", symbol: "USDS", name: "USDS", price: 0.9998, logo: "crypto/usds.webp" },
  { id: "cardano", symbol: "ADA", name: "Cardano", price: 0.2553, logo: "crypto/cardano.png" },
  { id: "leo-token", symbol: "LEO", name: "LEO Token", price: 8.98, logo: "crypto/leo-token.png" },
  { id: "rain", symbol: "RAIN", name: "Rain", price: 0.01126, logo: "crypto/rain.png" },
  { id: "stellar", symbol: "XLM", name: "Stellar", price: 0.2229, logo: "crypto/stellar.jpg" },
  { id: "near", symbol: "NEAR", name: "NEAR Protocol", price: 5, logo: "crypto/near.jpg" },
  { id: "bitcoin-cash", symbol: "BCH", name: "Bitcoin Cash", price: 317.71, logo: "crypto/bitcoin-cash.png" },
  { id: "uniswap", symbol: "UNI", name: "Uniswap", price: 9.07, logo: "crypto/uniswap.png" },
  { id: "litecoin", symbol: "LTC", name: "Litecoin", price: 70.7, logo: "crypto/litecoin.png" },
  { id: "canton-network", symbol: "CC", name: "Canton", price: 0.1283, logo: "crypto/canton-network.png" },
  { id: "sui", symbol: "SUI", name: "Sui", price: 1.21, logo: "crypto/sui.png" },
  { id: "avalanche-2", symbol: "AVAX", name: "Avalanche", price: 11.1, logo: "crypto/avalanche-2.png" },
  { id: "ethena-usde", symbol: "USDE", name: "Ethena USDe", price: 0.9996, logo: "crypto/ethena-usde.png" },
  { id: "dai", symbol: "DAI", name: "Dai", price: 1, logo: "crypto/dai.png" },
  { id: "hedera-hashgraph", symbol: "HBAR", name: "Hedera", price: 0.1034, logo: "crypto/hedera-hashgraph.png" },
  { id: "usd1-wlfi", symbol: "USD1", name: "USD1", price: 0.9996, logo: "crypto/usd1-wlfi.png" },
  { id: "the-open-network", symbol: "GRAM", name: "Gram (prev. Toncoin)", price: 1.53, logo: "crypto/the-open-network.png" },
  { id: "quant-network", symbol: "QNT", name: "Quant", price: 249.65, logo: "crypto/quant-network.jpg" },
  { id: "shiba-inu", symbol: "SHIB", name: "Shiba Inu", price: 0.00000596, logo: "crypto/shiba-inu.png" },
  { id: "bittensor", symbol: "TAO", name: "Bittensor", price: 304.79, logo: "crypto/bittensor.jpeg" },
  { id: "crypto-com-chain", symbol: "CRO", name: "Cronos", price: 0.06832, logo: "crypto/crypto-com-chain.png" },
  { id: "tether-gold", symbol: "XAUT", name: "Tether Gold", price: 4142.39, logo: "crypto/tether-gold.png" },
  { id: "bitway", symbol: "BTW", name: "Bitway", price: 1.23, logo: "crypto/bitway.png" },
  { id: "global-dollar", symbol: "USDG", name: "Global Dollar", price: 1, logo: "crypto/global-dollar.png" },
  { id: "pump-fun", symbol: "PUMP", name: "Pump.fun", price: 0.006517, logo: "crypto/pump-fun.jpg" },
  { id: "paypal-usd", symbol: "PYUSD", name: "PayPal USD", price: 0.9999, logo: "crypto/paypal-usd.png" },
  { id: "aave", symbol: "AAVE", name: "Aave", price: 179.36, logo: "crypto/aave.png" },
  { id: "okb", symbol: "OKB", name: "OKB", price: 121.84, logo: "crypto/okb.png" },
  { id: "ripple-usd", symbol: "RLUSD", name: "Ripple USD", price: 1, logo: "crypto/ripple-usd.png" },
  { id: "ethena", symbol: "ENA", name: "Ethena", price: 0.2413, logo: "crypto/ethena.png" },
  { id: "ondo-finance", symbol: "ONDO", name: "Ondo", price: 0.4964, logo: "crypto/ondo-finance.png" },
  { id: "hashnote-usyc", symbol: "USYC", name: "Circle USYC", price: 1.14, logo: "crypto/hashnote-usyc.png" },
  { id: "memecore", symbol: "M", name: "MemeCore", price: 1.04, logo: "crypto/memecore.png" },
  { id: "ondo-us-dollar-yield", symbol: "USDY", name: "Ondo US Dollar Yield", price: 1.15, logo: "crypto/ondo-us-dollar-yield.png" },
  { id: "sky", symbol: "SKY", name: "Sky", price: 0.09727, logo: "crypto/sky.jpg" },
  { id: "blackrock-usd-institutional-digital-liquidity-fund", symbol: "BUIDL", name: "BlackRock USD Institutional Digital Liquidity Fund", price: 1, logo: "crypto/blackrock-usd-institutional-digital-liquidity-fund.png" },
  { id: "worldcoin-wld", symbol: "WLD", name: "Worldcoin", price: 0.5795, logo: "crypto/worldcoin-wld.jpeg" },
  { id: "mantle", symbol: "MNT", name: "Mantle", price: 0.6566, logo: "crypto/mantle.png" },
  { id: "polkadot", symbol: "DOT", name: "Polkadot", price: 1.2, logo: "crypto/polkadot.jpg" },
  { id: "aster-2", symbol: "ASTER", name: "Aster", price: 0.7099, logo: "crypto/aster-2.png" },
  { id: "morpho", symbol: "MORPHO", name: "Morpho", price: 2.72, logo: "crypto/morpho.png" },
  { id: "internet-computer", symbol: "ICP", name: "Internet Computer", price: 3.37, logo: "crypto/internet-computer.png" },
  { id: "pepe", symbol: "PEPE", name: "Pepe", price: 0.00000437, logo: "crypto/pepe.jpeg" },
  { id: "falcon-finance", symbol: "USDF", name: "Falcon USD", price: 0.9961, logo: "crypto/falcon-finance.png" },
  { id: "pax-gold", symbol: "PAXG", name: "PAX Gold", price: 4147.21, logo: "crypto/pax-gold.png" },
  { id: "world-liberty-financial", symbol: "WLFI", name: "World Liberty Financial", price: 0.05515, logo: "crypto/world-liberty-financial.png" },
  { id: "united-stables", symbol: "U", name: "United Stables", price: 0.9992, logo: "crypto/united-stables.jpg" },
  { id: "htx-dao", symbol: "HTX", name: "HTX DAO", price: 0.00000172, logo: "crypto/htx-dao.png" },
  { id: "spiko-amundi-overnight-swap-fund-eur", symbol: "EURSAFO", name: "Spiko Amundi Overnight Swap Fund (EUR)", price: 1.14, logo: "crypto/spiko-amundi-overnight-swap-fund-eur.png" },
  { id: "usdd", symbol: "USDD", name: "USDD", price: 0.9993, logo: "crypto/usdd.jpg" },
  { id: "venice-token", symbol: "VVV", name: "Venice Token", price: 30.1, logo: "crypto/venice-token.png" },
  { id: "ethereum-classic", symbol: "ETC", name: "Ethereum Classic", price: 8.96, logo: "crypto/ethereum-classic.png" },
  { id: "bitget-token", symbol: "BGB", name: "Bitget Token", price: 2, logo: "crypto/bitget-token.png" },
  { id: "arbitrum", symbol: "ARB", name: "Arbitrum", price: 0.204, logo: "crypto/arbitrum.jpg" },
  { id: "bfusd", symbol: "BFUSD", name: "BFUSD", price: 0.9996, logo: "crypto/bfusd.png" },
  { id: "usdgo", symbol: "USDGO", name: "USDGO", price: 1, logo: "crypto/usdgo.png" },
  { id: "algorand", symbol: "ALGO", name: "Algorand", price: 0.132, logo: "crypto/algorand.png" },
  { id: "kaspa", symbol: "KAS", name: "Kaspa", price: 0.04256, logo: "crypto/kaspa.png" },
  { id: "polygon-ecosystem-token", symbol: "POL", name: "POL (ex-MATIC)", price: 0.1102, logo: "crypto/polygon-ecosystem-token.png" },
  { id: "gatechain-token", symbol: "GT", name: "Gate", price: 11.15, logo: "crypto/gatechain-token.png" },
  { id: "just", symbol: "JST", name: "JUST", price: 0.1398, logo: "crypto/just.jpg" },
  { id: "jupiter-exchange-solana", symbol: "JUP", name: "Jupiter", price: 0.3337, logo: "crypto/jupiter-exchange-solana.png" },
  { id: "kucoin-shares", symbol: "KCS", name: "KuCoin", price: 7.48, logo: "crypto/kucoin-shares.png" },
  { id: "render-token", symbol: "RENDER", name: "Render", price: 1.98, logo: "crypto/render-token.png" },
  { id: "blockchain-capital", symbol: "BCAP", name: "Blockchain Capital", price: 108.18, logo: "crypto/blockchain-capital.png" },
  { id: "pi-network", symbol: "PI", name: "Pi Network", price: 0.08727, logo: "crypto/pi-network.jpg" },
  { id: "cosmos", symbol: "ATOM", name: "Cosmos Hub", price: 1.75, logo: "crypto/cosmos.png" },
  { id: "lighter", symbol: "LIT", name: "Lighter", price: 3.66, logo: "crypto/lighter.png" },
  { id: "filecoin", symbol: "FIL", name: "Filecoin", price: 1.054, logo: "crypto/filecoin.png" },
  { id: "aerodrome-finance", symbol: "AERO", name: "Aerodrome Finance", price: 0.8667, logo: "crypto/aerodrome-finance.png" },
  { id: "nexo", symbol: "NEXO", name: "NEXO", price: 0.859, logo: "crypto/nexo.png" },
  { id: "pancakeswap-token", symbol: "CAKE", name: "PancakeSwap", price: 2.51, logo: "crypto/pancakeswap-token.png" },
  { id: "akedo", symbol: "AKE", name: "Akedo", price: 0.03358, logo: "crypto/akedo.png" },
  { id: "dash", symbol: "DASH", name: "Dash", price: 59.53, logo: "crypto/dash.png" },
  { id: "vechain", symbol: "VET", name: "VeChain", price: 0.008803, logo: "crypto/vechain.png" },
  { id: "injective-protocol", symbol: "INJ", name: "Injective", price: 7.56, logo: "crypto/injective-protocol.png" },
  { id: "superstate-short-duration-us-government-securities-fund-ustb", symbol: "USTB", name: "Invesco Short Duration US Government Securities Fund", price: 11.23, logo: "crypto/superstate-short-duration-us-government-securities-fund-ustb.png" },
  { id: "midnight-3", symbol: "NIGHT", name: "Midnight", price: 0.04421, logo: "crypto/midnight-3.png" },
  { id: "blockstack", symbol: "STX", name: "Stacks", price: 0.3903, logo: "crypto/blockstack.png" },
  { id: "ether-fi", symbol: "ETHFI", name: "Ether.fi", price: 0.742, logo: "crypto/ether-fi.jpeg" },
  { id: "stable-2", symbol: "STABLE", name: "​​Stable", price: 0.02653, logo: "crypto/stable-2.png" },
  { id: "layerzero", symbol: "ZRO", name: "LayerZero", price: 1.98, logo: "crypto/layerzero.jpeg" },
  { id: "gho", symbol: "GHO", name: "GHO", price: 0.9995, logo: "crypto/gho.png" },
  { id: "aptos", symbol: "APT", name: "Aptos", price: 0.8013, logo: "crypto/aptos.png" },
  { id: "open-usd", symbol: "OUSD", name: "Open USD", price: 0.9999, logo: "crypto/open-usd.png" },
];
