/** Top 100 US-listed, US-based companies by market cap (CoinCodex ranking, Oct 2026). Logos are bundled in public/stocks. */
export type StockInfo = { symbol: string; name: string; logo: string };

export const STOCK_CATALOG: StockInfo[] = [
  { symbol: "NVDA", name: "NVIDIA", logo: "stocks/NVDA.webp" },
  { symbol: "AAPL", name: "Apple", logo: "stocks/AAPL.webp" },
  { symbol: "GOOG", name: "Alphabet", logo: "stocks/GOOG.webp" },
  { symbol: "MSFT", name: "Microsoft", logo: "stocks/MSFT.webp" },
  { symbol: "AMZN", name: "Amazon", logo: "stocks/AMZN.webp" },
  { symbol: "SPCX", name: "SpaceX", logo: "stocks/SPCX.webp" },
  { symbol: "META", name: "Meta Platforms", logo: "stocks/META.webp" },
  { symbol: "AVGO", name: "Broadcom", logo: "stocks/AVGO.webp" },
  { symbol: "TSLA", name: "Tesla", logo: "stocks/TSLA.webp" },
  { symbol: "MU", name: "Micron Technology", logo: "stocks/MU.webp" },
  { symbol: "BRK.B", name: "Berkshire Hathaway", logo: "stocks/BRK-B.webp" },
  { symbol: "LLY", name: "Eli Lilly and", logo: "stocks/LLY.webp" },
  { symbol: "AMD", name: "Advanced Micro Devices", logo: "stocks/AMD.webp" },
  { symbol: "JPM", name: "JPMorgan Chase &", logo: "stocks/JPM.webp" },
  { symbol: "WMT", name: "Walmart", logo: "stocks/WMT.webp" },
  { symbol: "XOM", name: "Exxon Mobil", logo: "stocks/XOM.webp" },
  { symbol: "V", name: "Visa", logo: "stocks/V.webp" },
  { symbol: "JNJ", name: "Johnson & Johnson", logo: "stocks/JNJ.webp" },
  { symbol: "INTC", name: "Intel", logo: "stocks/INTC.webp" },
  { symbol: "MA", name: "Mastercard", logo: "stocks/MA.webp" },
  { symbol: "ABBV", name: "AbbVie", logo: "stocks/ABBV.webp" },
  { symbol: "CSCO", name: "Cisco Systems", logo: "stocks/CSCO.webp" },
  { symbol: "LRCX", name: "Lam Research", logo: "stocks/LRCX.webp" },
  { symbol: "PLTR", name: "Palantir Technologies", logo: "stocks/PLTR.webp" },
  { symbol: "AMAT", name: "Applied Materials", logo: "stocks/AMAT.webp" },
  { symbol: "CVX", name: "Chevron", logo: "stocks/CVX.webp" },
  { symbol: "ORCL", name: "Oracle", logo: "stocks/ORCL.webp" },
  { symbol: "COST", name: "Costco Wholesale", logo: "stocks/COST.webp" },
  { symbol: "CAT", name: "Caterpillar", logo: "stocks/CAT.webp" },
  { symbol: "BAC", name: "Bank of America", logo: "stocks/BAC.webp" },
  { symbol: "DELL", name: "Dell Technologies", logo: "stocks/DELL.webp" },
  { symbol: "KO", name: "Coca-Cola", logo: "stocks/KO.webp" },
  { symbol: "MRK", name: "Merck &", logo: "stocks/MRK.webp" },
  { symbol: "PG", name: "Procter & Gamble", logo: "stocks/PG.webp" },
  { symbol: "UNH", name: "UnitedHealth Group", logo: "stocks/UNH.webp" },
  { symbol: "PANW", name: "Palo Alto Networks", logo: "stocks/PANW.webp" },
  { symbol: "GE", name: "GE Aerospace", logo: "stocks/GE.webp" },
  { symbol: "MS", name: "Morgan Stanley", logo: "stocks/MS.webp" },
  { symbol: "PM", name: "Philip Morris International", logo: "stocks/PM.webp" },
  { symbol: "HD", name: "Home Depot", logo: "stocks/HD.webp" },
  { symbol: "NFLX", name: "Netflix", logo: "stocks/NFLX.webp" },
  { symbol: "CRWD", name: "CrowdStrike Holdings", logo: "stocks/CRWD.webp" },
  { symbol: "KLAC", name: "KLA", logo: "stocks/KLAC.webp" },
  { symbol: "TXN", name: "Texas Instruments", logo: "stocks/TXN.webp" },
  { symbol: "GS", name: "Goldman Sachs Group", logo: "stocks/GS.webp" },
  { symbol: "GEV", name: "GE Vernova", logo: "stocks/GEV.webp" },
  { symbol: "ANET", name: "Arista Networks", logo: "stocks/ANET.webp" },
  { symbol: "SNDK", name: "Sandisk", logo: "stocks/SNDK.webp" },
  { symbol: "RTX", name: "RTX", logo: "stocks/RTX.webp" },
  { symbol: "WFC", name: "Wells Fargo &", logo: "stocks/WFC.webp" },
  { symbol: "TMO", name: "Thermo Fisher Scientific", logo: "stocks/TMO.webp" },
  { symbol: "MRVL", name: "Marvell Technology", logo: "stocks/MRVL.webp" },
  { symbol: "C", name: "Citigroup", logo: "stocks/C.webp" },
  { symbol: "AMGN", name: "Amgen", logo: "stocks/AMGN.webp" },
  { symbol: "APH", name: "Amphenol", logo: "stocks/APH.webp" },
  { symbol: "IBM", name: "International Business Machines", logo: "stocks/IBM.webp" },
  { symbol: "AXP", name: "American Express", logo: "stocks/AXP.webp" },
  { symbol: "ADI", name: "Analog Devices", logo: "stocks/ADI.webp" },
  { symbol: "QCOM", name: "QUALCOMM", logo: "stocks/QCOM.webp" },
  { symbol: "CRM", name: "Salesforce", logo: "stocks/CRM.webp" },
  { symbol: "VZ", name: "Verizon Communications", logo: "stocks/VZ.webp" },
  { symbol: "DE", name: "Deere &", logo: "stocks/DE.webp" },
  { symbol: "GILD", name: "Gilead Sciences", logo: "stocks/GILD.webp" },
  { symbol: "DIS", name: "Walt Disney", logo: "stocks/DIS.webp" },
  { symbol: "TMUS", name: "T-Mobile US", logo: "stocks/TMUS.webp" },
  { symbol: "PEP", name: "PepsiCo", logo: "stocks/PEP.webp" },
  { symbol: "SCCO", name: "Southern Copper", logo: "stocks/SCCO.webp" },
  { symbol: "SCHW", name: "Charles Schwab", logo: "stocks/SCHW.webp" },
  { symbol: "ABT", name: "Abbott Laboratories", logo: "stocks/ABT.webp" },
  { symbol: "T", name: "AT&T", logo: "stocks/T.webp" },
  { symbol: "BLK", name: "BlackRock", logo: "stocks/BLK.webp" },
  { symbol: "UNP", name: "Union Pacific", logo: "stocks/UNP.webp" },
  { symbol: "MCD", name: "McDonald's", logo: "stocks/MCD.webp" },
  { symbol: "WELL", name: "Welltower", logo: "stocks/WELL.webp" },
  { symbol: "NEE", name: "NextEra Energy", logo: "stocks/NEE.webp" },
  { symbol: "PFE", name: "Pfizer", logo: "stocks/PFE.webp" },
  { symbol: "COP", name: "ConocoPhillips", logo: "stocks/COP.webp" },
  { symbol: "BA", name: "Boeing", logo: "stocks/BA.webp" },
  { symbol: "IBKR", name: "Interactive Brokers Group", logo: "stocks/IBKR.webp" },
  { symbol: "DHR", name: "Danaher", logo: "stocks/DHR.webp" },
  { symbol: "TJX", name: "TJX Companies", logo: "stocks/TJX.webp" },
  { symbol: "GLW", name: "Corning", logo: "stocks/GLW.webp" },
  { symbol: "NOW", name: "ServiceNow", logo: "stocks/NOW.webp" },
  { symbol: "ISRG", name: "Intuitive Surgical", logo: "stocks/ISRG.webp" },
  { symbol: "WDC", name: "Western Digital", logo: "stocks/WDC.webp" },
  { symbol: "UBER", name: "Uber Technologies", logo: "stocks/UBER.webp" },
  { symbol: "BX", name: "Blackstone", logo: "stocks/BX.webp" },
  { symbol: "FTNT", name: "Fortinet", logo: "stocks/FTNT.webp" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals", logo: "stocks/VRTX.webp" },
  { symbol: "NET", name: "Cloudflare", logo: "stocks/NET.webp" },
  { symbol: "BMY", name: "Bristol-Myers Squibb", logo: "stocks/BMY.webp" },
  { symbol: "BKNG", name: "Booking Holdings", logo: "stocks/BKNG.webp" },
  { symbol: "MPC", name: "Marathon Petroleum", logo: "stocks/MPC.webp" },
  { symbol: "PH", name: "Parker-Hannifin", logo: "stocks/PH.webp" },
  { symbol: "PGR", name: "Progressive", logo: "stocks/PGR.webp" },
  { symbol: "NEM", name: "Newmont", logo: "stocks/NEM.webp" },
  { symbol: "PLD", name: "Prologis", logo: "stocks/PLD.webp" },
  { symbol: "COF", name: "Capital One Financial", logo: "stocks/COF.webp" },
  { symbol: "SNOW", name: "Snowflake", logo: "stocks/SNOW.webp" },
  { symbol: "VLO", name: "Valero Energy", logo: "stocks/VLO.webp" },
];
